### ISSUE TITLE
【提问】请问有打算上架curseforge么？

### ISSUE THREAD

**Issue by bling-yshs** [ODDCraft/RoughlyEnoughCharacters#3]
如题;w;

**Comment by oott123** [comment]
没有。

**Comment by Indekkusu545** [comment]
建议上架curseforge。Modrinth又又又崩溃啦。
![image](https://user-images.githubusercontent.com/30483813/154836810-a0b00a91-52f7-4309-a99a-78c5f5837944.png)

**Comment by oott123** [comment]
如果需要，也可以从 GitHub Release 进行下载： https://github.com/oott123/RoughlyEnoughCharacters/releases

Curseforge 采用的 CloudFlare 防护规则会拦住我的访问，我懒得花时间对付它，在此问题缓解之前，暂时不作考虑。
