### ISSUE TITLE
1.18.2与应用能源2不兼容

### ISSUE THREAD

**Issue by EmiliatanMajiTennshi** [ODDCraft/RoughlyEnoughCharacters#7]
多次排查, 装了该mod, AE2的终端面板打不开

**Comment by NatsumiXD** [comment]
一个移除ae2支持的版本（乱改的，勉强能用）
[[拼音输入]roughly-enough-characters-0.0.4+1.18.2-fabric0.13.3.zip](https://github.com/oott123/RoughlyEnoughCharacters/files/8799968/roughly-enough-characters-0.0.4%2B1.18.2-fabric0.13.3.zip)
）

**Comment by oott123** [comment]
确认与 [fabric 11.0.0](https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/fabric%2Fv11.0.0) 不兼容

**Comment by oott123** [comment]
fixed in f4067dabe430641f9a77152769a01d83bfdc5fc2

**Comment by oott123** [comment]
https://modrinth.com/mod/roughly-enough-characters/version/0.0.5+1.18.2-fabric0.13.3

应当已经修复。如仍有问题，请继续反馈。

**Comment by EmiliatanMajiTennshi** [comment]
感谢更新, 已下载最新版, 目前一切正常
















在 2022-05-31 10:42:27，"三三" ***@***.***> 写道：

https://modrinth.com/mod/roughly-enough-characters/version/0.0.5+1.18.2-fabric0.13.3

应当已经修复。如仍有问题，请继续反馈。
