### ISSUE TITLE
请求添加Tom存储支持，尝试了下构建但游戏内未起作用

### ISSUE THREAD

**Issue by KuroPeach** [ODDCraft/RoughlyEnoughCharacters#8]
![image](https://user-images.githubusercontent.com/19620848/173593505-81dc7f1a-20ac-4a6c-b852-acb13bd9a640.png)
![image](https://user-images.githubusercontent.com/19620848/173593636-52ca2cfe-236a-42ae-8358-01c5b2ee0f31.png)
![image](https://user-images.githubusercontent.com/19620848/173594221-90c1e825-8b3e-4a5f-802e-c9fc87d8a714.png)

**Comment by KuroPeach** [comment]
主要是不知道" ()V "改写成啥

**Comment by vfyjxf** [comment]
你这个是target写错了，tom存储用正则表达式匹配的，但target写的却是String.contains

**Comment by KuroPeach** [comment]
原来如此
